services:
  - type: web
    name: projeto-barbearia
    env: node
    branch: main
    buildCommand: npm install --prefix backend
    startCommand: node backend/src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false