services:
  - type: web
    name: projeto-barbearia
    env: node
    branch: main
    buildCommand: npm install --prefix backend
    startCommand: node backend/src/app.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: https://dkeipxtsepodypcuwbbu.supabase.co
        sync: false
      - key: sb_publishable_GUUQBPp6XBke1I3jAWWsXw_Z_bOHWwh
        sync: false